services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: wesmooth-zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: wesmooth-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "event_blueprintexecution:1:1"
    networks:
      - kafka-net
  mongodb:
    image: 'mongo:latest'
    container_name: wesmooth-mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=developmentdb'
    ports:
      - '27017:27017'
networks:
  kafka-net:
    driver: bridge